# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'el.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 896)
        MainWindow.setMinimumSize(QtCore.QSize(200, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.FLButton = QtWidgets.QPushButton(self.centralwidget)
        self.FLButton.setObjectName("FLButton")
        self.verticalLayout.addWidget(self.FLButton)
        self.FLButton.setCheckable(True)

        self.SLButton = QtWidgets.QPushButton(self.centralwidget)
        self.SLButton.setObjectName("SLButton")
        self.verticalLayout.addWidget(self.SLButton)

        self.TPointButton = QtWidgets.QPushButton(self.centralwidget)
        self.TPointButton.setObjectName("TPointButton")
        self.verticalLayout.addWidget(self.TPointButton)

        self.EllCenButton = QtWidgets.QPushButton(self.centralwidget)
        self.EllCenButton.setObjectName("EllCenButton")
        self.verticalLayout.addWidget(self.EllCenButton)

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setDisabled(True)
        self.lineEdit.setText("safsd")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FLButton.setText(_translate("MainWindow", " First Line"))
        self.SLButton.setText(_translate("MainWindow", "Second Line"))
        self.TPointButton.setText(_translate("MainWindow", "Tangent point"))
        self.EllCenButton.setText(_translate("MainWindow", "Ellipse Center"))
